### ISSUE TITLE
Modified qsort1 to sort structs, invariant error

### ISSUE THREAD

**Issue by leowweixiang** [cverified/cbench-vst#4]
Hello, I'm new to VST, apologies if this is a simple error.

I'm trying to modify qsort1 to sort structs instead of floats. The change simply wraps the doubles in a struct:

```
//double a[N];

struct doublewrap {
	double value;
};

struct doublewrap a[N];

void
quicksort(int m, int n)
{
  int i, j;
  double pivot, tmp;

  if (m < n) {	//invariant error here
    pivot = a[n].value;	//passes clightgen; not sure if problem, but I can't even get here
    ...
```
Proof modification:

```
(*Require Import qsort1.*) Require Import qsort_wrap.
...
Definition t_struct_doublewrap := Tstruct _doublewrap noattr.
Eval compute in reptype t_struct_doublewrap. (*val*)
...
Definition quicksort_spec :=
 DECLARE _quicksort
  WITH gv : globals, m: int, n: int, before: list val, al: list val, after: list val
  PRE  [ tint, tint] 
    ...
    SEP(data_at Ews (tarray t_struct_doublewrap N) (*<-- replace tdouble*)
             (before ++ al ++ after) (gv _a))
  POST [ tvoid ]
    EX bl: list val,
     ...
    SEP(data_at Ews (tarray t_struct_doublewrap N) (*<-- replace tdouble*)
             (before ++ bl ++ after) (gv _a)).
```

However, at the first forward_if in the proof, I come across an issue replacing tdouble with t_struct_doublewrap:

```
Lemma body_quicksort:  semax_body Vprog Gprog f_quicksort quicksort_spec.
Proof.
start_function.
rename H0 into Hdef_al.
(************************************************)
(*If I put tarray tdouble (which is incorrect), the whole thing resolves fine to environ->mpred*)
Check (EX bl:list val, 
              PROP(Permutation al bl; sorted (f_cmp Cle) bl) LOCAL()
    SEP(data_at Ews (tarray tdouble N)
             (before ++ bl ++ after) (gv _a))).
(*But if I use tstruct, PROP...SEP is already an environ->mpred and causes an error*)
Check (EX bl:list val, 
              PROP(Permutation al bl; sorted (f_cmp Cle) bl) LOCAL()
    SEP(data_at Ews (tarray t_struct_doublewrap N)
             (before ++ bl ++ after) (gv _a))).
(************************************************)
forward_if (EX bl:list val, 
              PROP(Permutation al bl; sorted (f_cmp Cle) bl) LOCAL()
    SEP(data_at Ews (tarray t_struct_doublewrap N)
             (before ++ bl ++ after) (gv _a))). (*error*)
```
The error in question:
```
The term
 "PROP (Permutation al bl; sorted (f_cmp Cle) bl)
  LOCAL ()
  SEP (data_at Ews (tarray t_struct_doublewrap N) (before ++ bl ++ after) (gv _a))"
has type "environ -> mpred" while it is expected to have type 
"mpred".
```

Could I get any advice? I'm not in the VST mailing list at the moment, will be glad to send my files by direct email.

Regards,
Leow Wei Xiang

**Comment by andrew-appel** [comment]
Very likely the problem is this (which has nothing to do with structs):
Instead of writing:   ` forward_if (my-assertion...). `
write this:     `forward_if (my-assertion...)%assert.`

This is sometimes necessary because Coq gets confused about which notation scope to use.

On the other hand, you should be aware that struct-copying is not supported by VST.  It should work OK if you copy the individual fields of the struct.  I recommend you use the current master branch of VST, if you're not already doing to.

**Comment by leowweixiang** [comment]
Hello Andrew, I'm able to get past the forward_if now, thanks! Am aware of the struct-copying

**Comment by andrew-appel** [comment]
By the way, when I wrote "use the current master branch", I see that there are some incompatibilities, so wait until I push a new cbench-vst commit that references this issue, before pulling VST.

**Comment by andrew-appel** [comment]
OK, with commit 081469e now up to date with latest VST.
